### ISSUE TITLE
change Cypress tests so that they don't use cy.visit() to access a page other than the home page

### ISSUE THREAD

**Issue by ZathrasXI** [uob-group-10-mynt/mynt-finance-banking-app#102]
By navigating to a page using the URL we aren't testing the functionality of the navbar/drawer. The tests could be improved by clicking on the navbar and then the correct link, to get to the page.

![Image](https://github.com/uob-group-10-mynt/mynt-finance-banking-app/assets/69600324/56d1346e-0080-4440-91cc-a1f8a399ae97)

**Comment by theCyberExorcist** [comment]
> By navigating to a page using the URL we aren't testing the functionality of the navbar/drawer. The tests could be improved by clicking on the navbar and then the correct link, to get to the page.

I did navbar/drawer routing tests in drawer.cy.js to separate them from pages tests. In this way, changes of navbar would only affect drawer tests, so that pages tests could still pass without modification.
