### ISSUE TITLE
user can log in - frontend

### ISSUE THREAD

**Issue by LurchK** [uob-group-10-mynt/mynt-finance-banking-app#48]
Request from frontend to backend, with correct credentials logs user in. UI shows that user is logged in.

Acceptance criteria:
- [x] when correct credentials are sent to backend, then 200 code and JWTs are received and user is redirected to home page
- [x] when incorrect credentials are sent to backend, error code is received, and page displays error
- [x] when user is logged in, log in button is hidden and log out button is displayed
- [x] when a user clicks log out, they are logged out
- [x] Cypress tests for correct and incorrect credentials

**Comment by ZathrasXI** [comment]
Save JWTs in session storage instead of localstorage -[users will be logged out when they close the tab](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage), which is more secure.
