### ISSUE TITLE
KYC Research

### ISSUE THREAD

**Issue by LurchK** [uob-group-10-mynt/mynt-finance-banking-app#52]
- KYC requirements in Kenya available at [here](https://shuftipro.com/compliances-reports/kenya.pdf)
- [How Monzo do KYC digitally](https://monzo.com/help/opening-an-account/why-we-ask-for-a-video-when-you-open-a-monzo-account/)

**Comment by JamesLove1** [comment]
results please see excel file wiithin onedrive research folder
